# Generated by Django 4.2.3 on 2023-07-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifier', models.CharField(max_length=256, verbose_name='Certifier')),
                ('cert_name', models.CharField(default='Proficiency Certificate', max_length=256, verbose_name='Certificate Name')),
                ('date_achieved', models.DateField(default=None, verbose_name='Date Achieved')),
                ('link', models.URLField(default='https://mhealy.dev', max_length=256, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256, verbose_name='Company')),
                ('position', models.CharField(default=None, max_length=256, verbose_name='Position')),
                ('description', models.CharField(default=None, max_length=2048, verbose_name='Description')),
                ('start_year', models.CharField(max_length=4, verbose_name='Start Year')),
                ('end_year', models.CharField(default='now', max_length=4, verbose_name='End Year')),
                ('link', models.URLField(default='https://mhealy.dev', max_length=256, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('years', models.IntegerField(verbose_name='Years')),
                ('link', models.URLField(default='https://mhealy.dev', max_length=256, verbose_name='Link')),
                ('icon', models.URLField(default='', max_length=256, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name', 'years'],
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.CharField(blank=True, default=None, max_length=2048, verbose_name='Description')),
                ('repository', models.URLField(blank=True, default=None, max_length=256, verbose_name='Repository')),
                ('skills_used', models.ManyToManyField(blank=True, related_name='skills', to='portfolio.skill', verbose_name='Skills Used')),
            ],
        ),
    ]
