# Generated by Django 4.2.3 on 2023-08-04 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cert',
            options={'ordering': ['-pk'], 'verbose_name': 'Cert', 'verbose_name_plural': 'Certs'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['year_created'], 'verbose_name': 'Code'},
        ),
        migrations.AlterModelOptions(
            name='exp',
            options={'ordering': ['-pk'], 'verbose_name': 'Exp'},
        ),
        migrations.AddField(
            model_name='code',
            name='year_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Year Created'),
        ),
    ]
